github-token = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

github-name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

your-ıp-address = ["XXX.XXX.XXX.XXX/32"]

key_name = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

hosted-zone = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

server-name = "nXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
